module.exports = {
  preset: 'react-native',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  setupFilesAfterEnv: ['<rootDir>/__tests__/setup.ts'],
  testEnvironment: 'node',
  transformIgnorePatterns: [
    'node_modules/(?!(react-native|@react-native|@react-navigation|@gluestack-ui|@gluestack-style|react-native-reanimated|react-native-safe-area-context|@tanstack/react-query|zustand|react-native-push-notification|react-native-image-picker|react-native-video|react-native-video-processing|react-native-keychain|react-native-device-info|react-native-permissions|react-native-otp-textinput|react-native-confetti-cannon|react-native-indicators|react-native-svg|react-native-community|react-native-community/netinfo|lottie-react-native|lucide-react-native|moti|i18next|@expo)/)',
  ],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@components/(.*)$': '<rootDir>/src/components/$1',
    '^@screens/(.*)$': '<rootDir>/src/screens/$1',
    '^@navigation/(.*)$': '<rootDir>/src/navigation/$1',
    '^@services/(.*)$': '<rootDir>/src/services/$1',
    '^@stores/(.*)$': '<rootDir>/src/stores/$1',
    '^@hooks/(.*)$': '<rootDir>/src/hooks/$1',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
    '^@types/(.*)$': '<rootDir>/src/types/$1',
    '^@constants/(.*)$': '<rootDir>/src/constants/$1',
    '^@assets/(.*)$': '<rootDir>/src/assets/$1',
    // Mock custom components - let jest.mock() in test files handle @/components
    '^../../components$': '<rootDir>/__tests__/__mocks__/components.js',
    '^../components$': '<rootDir>/__tests__/__mocks__/components.js',
    // Note: @/components is mocked via jest.mock() in test files, not via moduleNameMapper
    '^../../components/toast$': '<rootDir>/__tests__/__mocks__/components/toast.js',
    '^../components/toast$': '<rootDir>/__tests__/__mocks__/components/toast.js',
    '^@/components/toast$': '<rootDir>/__tests__/__mocks__/components/toast.js',
    // Mock utils
    '^../../utils/colors$': '<rootDir>/__tests__/__mocks__/utils/colors.js',
    '^../utils/colors$': '<rootDir>/__tests__/__mocks__/utils/colors.js',
    '^@/utils/colors$': '<rootDir>/__tests__/__mocks__/utils/colors.js',
    // Mock constants
    '^@/constants$': '<rootDir>/__tests__/__mocks__/constants.js',
    '^@/constants/(.*)$': '<rootDir>/__tests__/__mocks__/constants.js',
    // Mock React Native modules
    '^react-native$': '<rootDir>/__tests__/__mocks__/react-native.js',
    '^react-native-push-notification$': '<rootDir>/__tests__/__mocks__/react-native-push-notification.js',
    '^react-native-image-picker$': '<rootDir>/__tests__/__mocks__/react-native-image-picker.js',
    '^react-native-video$': '<rootDir>/__tests__/__mocks__/react-native-video.js',
    '^react-native-video-processing$': '<rootDir>/__tests__/__mocks__/react-native-video-processing.js',
    '^react-native-keychain$': '<rootDir>/__tests__/__mocks__/react-native-keychain.js',
    '^react-native-device-info$': '<rootDir>/__tests__/__mocks__/react-native-device-info.js',
    '^react-native-permissions$': '<rootDir>/__tests__/__mocks__/react-native-permissions.js',
    '^react-native-otp-textinput$': '<rootDir>/__tests__/__mocks__/react-native-otp-textinput.js',
    '^react-native-confetti-cannon$': '<rootDir>/__tests__/__mocks__/react-native-confetti-cannon.js',
    '^react-native-indicators$': '<rootDir>/__tests__/__mocks__/react-native-indicators.js',
    '^react-native-svg$': '<rootDir>/__tests__/__mocks__/react-native-svg.js',
    '^@react-native-community/netinfo$': '<rootDir>/__tests__/__mocks__/react-native-community-netinfo.js',
    '^lottie-react-native$': '<rootDir>/__tests__/__mocks__/lottie-react-native.js',
    '^lucide-react-native$': '<rootDir>/__tests__/__mocks__/lucide-react-native.js',
    '^moti$': '<rootDir>/__tests__/__mocks__/moti.js',
    '^i18next$': '<rootDir>/__tests__/__mocks__/i18next.js',
    '^zustand$': '<rootDir>/__tests__/__mocks__/zustand.js',
    '^@tanstack/react-query$': '<rootDir>/__tests__/__mocks__/react-query.js',
    '^@gluestack-ui/(.*)$': '<rootDir>/__tests__/__mocks__/gluestack-ui.js',
    '^@gluestack-style/react$': '<rootDir>/__tests__/__mocks__/gluestack-style.js',
    '^@gluestack-ui/config$': '<rootDir>/__tests__/__mocks__/gluestack-ui-config.js',
    '^@gluestack-ui/themed$': '<rootDir>/__tests__/__mocks__/gluestack-ui-themed.js',
    '^react-native-reanimated$': '<rootDir>/__tests__/__mocks__/react-native-reanimated.js',
  },
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!src/**/*.d.ts',
    '!src/**/index.ts',
    '!src/**/*.stories.{ts,tsx}',
    '!src/components/**/*', // Exclude UI components from coverage
    '!src/navigation/**/*', // Exclude navigation from coverage
  ],
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 70,
      lines: 70,
      statements: 70,
    },
  },
  testMatch: [
    '<rootDir>/__tests__/**/*.test.{ts,tsx}',
    '<rootDir>/src/**/__tests__/*.test.{ts,tsx}',
  ],
  modulePathIgnorePatterns: ['<rootDir>/node_modules/'],
  testTimeout: 30000,
};
