// Mock constants for testing
module.exports = {
  APP_CONFIG: {
    apiUrl: 'http://localhost:3000/api',
    environment: 'test',
    version: '1.0.0',
    buildNumber: '1',
  },
  API_ENDPOINTS: {
    AUTH: {
      SEND_OTP: '/students/send-otp',
      VERIFY_OTP: '/students/verify-otp',
      REGISTER: '/students/register',
      LOGOUT: '/auth/logout',
    },
    DASHBOARD: {
      GET: '/dashboard',
    },
    USER: {
      UPDATE_PROFILE: '/students/profile',
    },
    VIDEO: {
      UPLOAD: '/video/upload',
    },
    SUBSCRIPTION: {
      UPDATE: '/subscription/update',
    },
  },
  STORAGE_KEYS: {
    AUTH_TOKENS: 'auth_tokens',
    USER_DATA: 'user_data',
    APP_SETTINGS: 'app_settings',
    CACHED_DATA: 'cached_data',
    THEME: 'theme',
    LANGUAGE: 'language',
  },
  SECURE_STORAGE_KEYS: {
    BIOMETRIC_ENABLED: 'biometric_enabled',
    PIN_CODE: 'pin_code',
    ENCRYPTION_KEY: 'encryption_key',
  },
  API: {
    TIMEOUT: 30000,
    RETRY_ATTEMPTS: 3,
    RETRY_DELAY: 1000,
    CACHE_TIME: 5 * 60 * 1000,
    STALE_TIME: 2 * 60 * 1000,
  },
  VALIDATION: {
    EMAIL_REGEX: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
    PHONE_REGEX: /^\d{10}$/,
    PINCODE_REGEX: /^\d{6}$/,
    PASSWORD_MIN_LENGTH: 8,
    NAME_MIN_LENGTH: 2,
    NAME_MAX_LENGTH: 50,
  },
  ERROR_MESSAGES: {
    NETWORK_ERROR: 'Network error. Please check your connection.',
    UNAUTHORIZED: 'You are not authorized to perform this action.',
    FORBIDDEN: 'Access denied.',
    NOT_FOUND: 'Resource not found.',
    SERVER_ERROR: 'Server error. Please try again later.',
    VALIDATION_ERROR: 'Please check your input and try again.',
    UNKNOWN_ERROR: 'An unknown error occurred.',
  },
  SUCCESS_MESSAGES: {
    LOGIN_SUCCESS: 'Login successful!',
    REGISTRATION_SUCCESS: 'Registration successful!',
    PROFILE_UPDATED: 'Profile updated successfully!',
    PASSWORD_CHANGED: 'Password changed successfully!',
    LOGOUT_SUCCESS: 'Logged out successfully!',
  },
  SUPPORTED_LANGUAGES: {
    EN: 'en',
    HI: 'hi',
    TE: 'te',
  },
  DEFAULT_LANGUAGE: 'en',
  BIOMETRIC_TYPES: {
    FACE_ID: 'FaceID',
    TOUCH_ID: 'TouchID',
    FINGERPRINT: 'Fingerprint',
  },
  QUIZ: {
    TIME_LIMIT: 30,
    PASSING_SCORE: 70,
    MAX_QUESTIONS: 10,
  },
  ANIMATION: {
    DURATION: {
      FAST: 200,
      NORMAL: 300,
      SLOW: 500,
    },
    EASING: {
      EASE_IN: 'ease-in',
      EASE_OUT: 'ease-out',
      EASE_IN_OUT: 'ease-in-out',
    },
  },
  SUBSCRIPTION: {
    PLANS: {
      FREE: 'free',
      PREMIUM: 'premium',
    },
    PRICING: {
      PREMIUM_ANNUAL: 100,
    },
    FEATURES: {
      FREE: ['Basic quiz access', 'Event browsing'],
      PREMIUM: ['Full quiz access', 'Ad-free experience', 'Priority support'],
    },
  },
  PAYMENT_METHODS: {
    CASH: 'cash',
    CHEQUE: 'cheque',
    RAZORPAY: 'razorpay',
    STRIPE: 'stripe',
    PAYTM: 'paytm',
  },
  VIDEO_UPLOAD: {
    MIN_DURATION: 30,
    MAX_DURATION: 180,
    MAX_FILE_SIZE: 100 * 1024 * 1024,
    SUPPORTED_FORMATS: ['mp4', 'mov', 'avi'],
    QUALITY: {
      COMPRESSION: 0.8,
      RESOLUTION: '720p',
    },
  },
  NOTIFICATION_TYPES: {
    EVENT: 'event',
    QUIZ: 'quiz',
    RESULT: 'result',
    SUBSCRIPTION: 'subscription',
    GENERAL: 'general',
  },
  SCHOOL: {
    INVITATION_EXPIRY_DAYS: 7,
    MAX_STUDENTS_PER_SCHOOL: 1000,
    SUPPORTED_GRADES: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'],
  },
  EVENT_CATEGORIES: [
    'National Anthem',
    'Tongue Twister',
    'Singing',
    'Dancing',
    'Movie dialogues',
    'Comedy Act / Skit',
    'Shayari',
    'Rhymes',
    'Poems',
    'Cooking',
    'Twins Act',
    'Any special Talent',
    'Mom and Kid Act',
    'Craft Making',
    'Kids group performance with teacher',
  ],
  NAVIGATION: {
    ANIMATION_DURATION: 300,
    HEADER_HEIGHT: 56,
    TAB_BAR_HEIGHT: 83,
  },
  COLORS: {
    LIGHT: {
      primary: '#007AFF',
      secondary: '#5856D6',
      background: '#FFFFFF',
      surface: '#F2F2F7',
      text: '#000000',
      textSecondary: '#8E8E93',
      border: '#C6C6C8',
      error: '#FF3B30',
      success: '#34C759',
      warning: '#FF9500',
      info: '#007AFF',
    },
    DARK: {
      primary: '#0A84FF',
      secondary: '#5E5CE6',
      background: '#000000',
      surface: '#1C1C1E',
      text: '#FFFFFF',
      textSecondary: '#8E8E93',
      border: '#38383A',
      error: '#FF453A',
      success: '#32D74B',
      warning: '#FF9F0A',
      info: '#0A84FF',
    },
  },
};